# Generated by Django 3.0.4 on 2020-04-18 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
            ],
            options={
                'verbose_name': 'Tree ',
                'verbose_name_plural': 'Trees',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childrenMissing', models.IntegerField(default=62)),
                ('number', models.IntegerField(default=1)),
                ('child1', models.IntegerField()),
                ('child1Value', models.IntegerField(default=0)),
                ('child2', models.IntegerField()),
                ('child2Value', models.IntegerField(default=0)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Tree', verbose_name='related tree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'A node',
                'verbose_name_plural': 'Nodes',
            },
        ),
        migrations.CreateModel(
            name='ChildNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('children', models.IntegerField(default=0)),
                ('parentNode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Node', verbose_name='Child')),
            ],
        ),
    ]
