# Generated by Django 3.0.4 on 2020-04-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='json_string',
            field=models.TextField(null=True, verbose_name=''),
        ),
    ]
