# Generated by Django 3.0.4 on 2020-03-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
