# Generated by Django 3.0.4 on 2020-05-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_tree_json_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name=''),
        ),
    ]
