# Generated by Django 3.0.4 on 2020-03-22 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_node_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='childrenMissing',
            field=models.IntegerField(default=62),
        ),
        migrations.CreateModel(
            name='ChildNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('children', models.IntegerField(default=0)),
                ('parentNode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Node', verbose_name='Child')),
            ],
        ),
    ]
