# Generated by Django 3.0.4 on 2020-03-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_auto_20200322_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='child1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='child1Value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='child2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='child2Value',
            field=models.IntegerField(default=0),
        ),
    ]
